chk live user passwd

diff --git a/configs/scripts/stages/19-manual-checks b/configs/scripts/stages/19-manual-checks
--- a/configs/scripts/stages/19-manual-checks
+++ b/configs/scripts/stages/19-manual-checks
@@ -77,3 +77,11 @@ check_initramfs_size
 
 search_initramfs_for plymouth
 search_initramfs_for crypttab
+
+
+# -- Check that the Live user password is not goddamn empty.
+
+if ! check_live_user_password; then
+    echo "Live user password is missing or blank"
+    exit 1
+fi
