update

diff --git a/configs/znx-gui b/configs/znx-gui
--- a/configs/znx-gui
+++ b/configs/znx-gui
@@ -1,251 +1,70 @@
 #! /bin/sh
 
-TITLE="znx GUI — Operating System Deployment Tool"
 
-GetDevice () {
-	echo $(kdialog \
-		--style breeze \
-		--title "$TITLE" \
-		--combobox "Select a target device to continue." $(lsblk -npdlo NAME))
+# -- Variables.
+
+TITLE=ZNX_GUI
+STYLE=breeze
+
+set -x
+
+
+# -- Functions for the GUI.
+
+alias ui="kdialog --title='$TITLE'"
+
+error () { ui --error "$@"; exit 1; }
+notify () { ui --passivepopup "$@" 5; }
+ask () { ui --yesno "$@"; }
+as_root () { ui --password "Password:" | sudo -Sk $@; }
+
+CMDS="init restore-esp deploy update revert remove clean reset stats"
+
+select_command () { ui --combobox "Command to run:" $CMDS; }
+select_device () { ui --combobox "Device:" $(lsblk -npdlo NAME); }
+select_image () { ui --combobox "Image:" $(as_root ./znx list $DEVICE); }
+
+get_url () { ui --inputbox "File to deploy (URL or path):"; }
+get_image () { ui --inputbox "Image name:"; }
+
+
+# -- Wrappers for znx's commands.
+
+_znx_gui_init () { as_root ./znx init $DEVICE; }
+_znx_gui_restore_esp () { as_root ./znx restore-esp $DEVICE; }
+_znx_gui_deploy () { as_root ./znx deploy $DEVICE $(get_image) $(eval echo $(get_url)); }
+_znx_gui_update () { as_root ./znx update $DEVICE $(select_image); }
+_znx_gui_revert () { as_root ./znx revert $DEVICE $(select_image); }
+_znx_gui_remove () { as_root ./znx remove $DEVICE $(select_image); }
+_znx_gui_clean () { as_root ./znx clean $DEVICE $(select_image); }
+_znx_gui_reset () { as_root ./znx reset $DEVICE $(select_image); }
+
+_znx_gui_stats () {
+    TMP_FILE=$(mktemp)
+    as_root ./znx stats $DEVICE $(select_image) > $TMP_FILE
+    ui --textbox $TMP_FILE
+    rm -rf $TMP_FILE
 }
 
-GetName () {
-	echo $(kdialog \
-		--style breeze \
-		--title "$TITLE" \
-		--inputbox "Name of ISO image to deploy." "nitrux/stable")
-}
 
-GetPath () {
-	echo $(kdialog \
-		--style breeze \
-		--title "$TITLE" \
-		--inputbox "Enter the path or the remote URL of the ISO file." "/home/user/nitrux.iso")
-}
-
-showSuccess () {
-	kdialog \
-		--style breeze \
-		--title "Success — $TITLE" \
-		--msgbox "$1"
-}
-
-showUnexpectedError () {
-	kdialog \
-		--style breeze \
-		--title "Error — $TITLE" \
-		--error "Unexpected Error Occurred. Run znx in a Terminal for verbose output."
-}
-
-showProgressDialog () {
-	kdialog \
-		--title "$TITLE" \
-		--style breeze \
-		--msgbox "Please Wait, this may take some time.\nYou can close this window. This program will inform you when the process completes." &
-}
-
-showTextDialog () {
-	kdialog \
-		--title "$TITLE" \
-		--style breeze \
-		--textbox /tmp/znx_output
-}
-
-Init () {
-	echo "Initialize the storage device."
-
-	if kdialog --style breeze --yesno "This will wipe your device. Do you wish to proceed?."; then
-		DEVICE=$(GetDevice)
-
-		showProgressDialog
-
-		znx init $DEVICE &&
-			showSuccess "Device initialized." ||
-			showUnexpectedError
-	fi
-}
-
-Restore () {
-	echo "Restore the ESP (EFI System Partition) of the given device."
-
-		DEVICE=$(GetDevice)
-
-		showProgressDialog
-
-		znx restore $DEVICE &&
-			showSuccess "ESP (EFI System Partition) restored." ||
-			showUnexpectedError
-	fi
-}
-
-Deploy () {
-	echo "Deploy an image on a storage device."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-	IMAGEPATH=$(GetPath)
-
-	showProgressDialog	
-
-	znx deploy $DEVICE $IMAGENAME $IMAGEPATH &&
-		showSuccess "Successfully deployed $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Update () {
-	echo "Update the specified image."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showProgressDialog
-
-	znx update $DEVICE $IMAGENAME &&
-		showSuccess "Successfully updated $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Revert () {	
-	echo "Revert to the previous version of the image."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-	IMAGEPATH=$(GetPath)
-
-	showProgressDialog
-
-	znx revert $DEVICE $IMAGENAME &&
-		showSuccess "Successfully reverted $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Clean () {	
-	echo "Remove the backup that is created during an update."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showProgressDialog
-
-	znx clean $DEVICE $IMAGENAME &&
-		showSuccess "Successfully removed backup of $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Reset () {	
-	echo "Delete all user data of the specified image."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showProgressDialog
-
-	znx reset $DEVICE $IMAGENAME &&
-		showSuccess "Successfully cleaned user data of $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Remove () {	
-	echo "Remove the specified image."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showProgressDialog
-
-	znx remove $DEVICE $IMAGENAME &&
-		showSuccess "Successfully removed $IMAGENAME." ||
-		showUnexpectedError
-}
-
-Stats () {	
-	echo "Show statistics about the provided image."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showTextDialog
-
-	znx stats $DEVICE $IMAGENAME > /tmp/znx_output &&
-			showSuccess "Displaying statistics of $IMAGENAME" ||
-			showUnexpectedError
-	fi
-}
-
-List () {	
-	echo "List the deployed images."
-
-	DEVICE=$(GetDevice)
-	IMAGENAME=$(GetName)
-
-	showTextDialog
-
-	znx list $DEVICE > /tmp/znx_output &&
-			showSuccess "The following ISO files were found in $DEVICE." ||
-			showUnexpectedError
-	fi
-}
+# -- Loop until the user closes the main window.
 
 while :; do
-	OPTIONS="0 init on \
-	1 restore off \
-	2 deploy off \
-	3 update off \
-	4 revert off \
-	5 clean off \
-	6 reset off \
-	7 remove off \
-	8 stats off \
-	9 list off"
 
-	INPUT_OPTION=$(kdialog \
-					--style breeze \
-					--title "$TITLE" \
-					--radiolist "Select a command to continue" $OPTIONS)
+    COMMAND=$(select_command)
 
-	case "$INPUT_OPTION" in
-		0)
-			Init
-		;;
+    [ ${#COMMAND} -gt 0 ] ||
+        error "Operation cancelled."
 
-		1)
-			Restore
-		;;
+    DEVICE=$(select_device)
 
-		2)
-			Deploy
-		;;
+    notify "Please wait. You will be notified when the command finishes." &
 
-		3)
-			Update
-		;;
+    _znx_gui_$COMMAND &&
+        notify "Operation completed successfully." ||
+        error "Operation failed!"
 
-		4)
-			Revert
-		;;
+    ask "Do you want to perform another action?" ||
+        exit
 
-		5)
-			Clean
-		;;
-
-		6)
-			Reset
-		;;
-
-		7)
-			Remove
-		;;
-
-		8)
-			Stats
-		;;
-
-		9)
-			List
-		;;
-
-		*)
-			break
-		;;
-	esac
 done
